<?php $this->headTitle('Passport News'); ?>	
<div class="content-box">
	<div class="header">
		<h1><?= $this->article->SUBJECT ?></h1>
		<h2>
			posted on <?= $this->article->POSTED_ON ?> by 
			<?= $this->article->FIRST_NAME ?> <?= $this->article->LAST_NAME ?>
		</h2>
	</div>
 	<div class="body">
	 &nbsp;&nbsp;&nbsp;&nbsp;
	 <?= $this->article->BODY ?>
 	</div>
</div>

<div class="content-box">
	<div class="header">
		<h1>Edit Article</h1>
	</div>
 	<div class="body">
		<form method="post">
			<div>
				Subject
				<input type="text" name="subject" value="<?= $this->article->SUBJECT ?>" />
			</div>
			<div>
				<textarea name="body"><?= $this->article->BODY ?></textarea>
			</div>
			<select name="type">
				<option value="0">Information</option>
				<option value="1">Warning</option>
				<option value="2">Alert</option>
			</select>
			<input type="submit" value="Save" />
		</form>
 	</div>
</div>