<table>
	<thead>
		<tr>
			<th style="width: 0"></th>
			<?php foreach (array('Filename' => 'filename', 'Modified' => 'mtime', 'Size' => 'size') as $k => $v) : ?>
			<th>
				<?php echo $this->partial('downloads/partials/sort_header.phtml', array(
					'url' => "/downloads/?cwd=" . urlencode($this->cwd) . "&layout=small",
					'title' => $k, 
					'field' => $v, 
					'sort' => $this->sort)) ?>
			</th>
			<?php endforeach; ?>
		</tr>
	</thead>
	<tbody>
		<?php $alt = 0; foreach ($this->files->folders as $folder) : ?>
		<tr <?php if ($alt ^= 1) : ?>class="alt"<?php endif; ?>>
			<td style="padding-right: 5px; text-align: right">
				<img src="/images/icons/downloads/folder-small.png" alt="folder icon" />
			</td>
			<td>
				<a href="/downloads?cwd=<?php echo urlencode($this->cwd . $folder->filename) ?>&layout=small">
					<?php echo $folder->filename ?>
				</a>
			</td>
			<td>N/A</td>
			<td>N/A</td>
		</tr>
		<?php endforeach; ?>
		<?php 
		foreach ($this->files->files as $file) : 
			$iconPath = '/images/icons/downloads/default-small-icon.png';
			$ext = substr($file->filename, strrpos($file->filename, '.') + 1);
			$relPath = '/images/icons/downloads/' . $ext . '-small-icon.png';
			
			if (file_exists(APP_ROOT . '/htdocs' . $relPath))
				$iconPath = $relPath;
		?>
		<tr <?php if ($alt ^= 1) : ?>class="alt"<?php endif; ?>>
			<td style="padding-right: 5px; text-align: right">
				<img src="<?php echo $iconPath ?>" alt="<?php echo $ext ?> icon" />
			</td>
			<td>
				<a title="<?php echo $file->filename ?>"
					href="/downloads/download?file=<?php echo urlencode($file->filename) ?>&cwd=<?php echo urlencode($this->cwd) ?>">
					<?php if (strlen($file->filename) > 96) : ?>
					<?php echo substr($file->filename, 0, 96) . '...' ?>
					<?php else : ?>
					<?php echo $file->filename ?>
					<?php endif; ?>
				</a>
			</td>
			<td style="padding-left: 5px"><?php echo date('F d Y', $file->mtime) ?></td>
			<td style="padding-left: 5px"><?php echo $this->fileSize($file->size) ?></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>