<?php 
$this->headTitle('Passport Users'); 
$this->headLink()
	->appendStylesheet('/scripts/css/icons.css');

$this->layout()->help = array(
	'title' => 'Passport Users',
	'body' => 'This page provides a list of users as well as means to manage them.');
?>
<div class="content-box">
	<div class="header">
		<div style="float:right; padding-top: 5px; padding-right: 5px;">
			<a href="/users/create" title="Create User">
				<img class="icon" src="/images/icons/notes_16.png" alt="notes icon" />
			</a>
		</div>
		<h1>Passport Users</h1>
	</div>
	<div class="body">
		<table>
			<col style="width: 20px" />
			<col style="width: 200px" />
			<col style="width: 300px"/>
			<col style="text-align: right" />
			
			<thead>
				<tr>
					<th></th>
					<?php foreach (array('n' => 'Name', 'u' => 'Username', 'r' => 'Role') as $field_key => $field_name) : ?>
					<th>
						<?php if ($this->sort == $field_key) : ?>
						<img class="icon" src="/images/icons/<?php echo $this->order == 'desc' ? 'up' : 'down' ?>_16.png" />
						<?php endif ?>
						<a href="/users?page=<?php echo $this->paging->current ?>&sort=<?php echo $field_key ?>&order=<?php echo $this->sort == $field_key && $this->order == 'desc' ? 'asc' : 'desc' ?>"><?php echo $field_name ?></a>
					</th>
					<?php endforeach ?>
				</tr>
			</thead>
			<tbody>
				<? $alt = 0; foreach($this->users as $user) : ?>
				<tr<?php if ($alt^=1): ?> class="alt"<?php endif; ?>>
					<td>
						<a href="/users/delete/user/<?php echo $user->id ?>" title="Delete User">
							<img class="icon" src="/images/icons/trash_16.png" alt="trash icon" />
						</a>
					</td>
					<td><a href="/users/edit/user/<?php echo $user->id ?>"><?php echo $user->first_name ?> <?php $user->last_name ?></a></td>
					<td><?php echo $user->username ?></td>
					<td><?php echo ucwords($user->Role->name) ?></td>
				</tr>
				<? endforeach; ?>
				<tr>
					<td colspan="4" style="text-align: center">
						<?php if ($this->paging->current > 1) : ?>
							<a href="/users?page=<?php echo $this->paging->current - 1 ?>">&lt;&lt;Previous Page</a> - 
						<?php endif ?>
						Page <?php echo $this->paging->current ?> - 
						<?php if ($this->paging->current < $this->paging->pages) : ?>
						<a href="/users?page=<?php echo $this->paging->current + 1 ?>">Next Page &gt;&gt;</a>
						<?php endif ?>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>