<?php 
	$this->headTitle("Search Index Administration");
	$this->headScript()->appendFile("/scripts/js/ajax.js");
	$this->headLink()->appendStylesheet('/scripts/css/icons.css');
	
	$this->layout()->help = array(
		'title' => 'Search Admin',
		'body' => 'This page is designed to provide information and tools that help maintain the Lucene search system.');
?>
<style type="text/css">
	#progress_bar {
		border: 2px solid black;
		display: inline-block;
		width: 200px;
		height: 20px;
		background: gray;
	}
	
	#progress_bar div {
		border: 0;
		border-right: 1px solid black;
		display: inline-block;
		height: 20px;
		width: 0%;
		background: cyan;
	}
	
	.indicator {
		border: 2px solid black;
		display: inline-block;
		height: 20px;
		width: 20px;
		background: gray;
	}
</style>
<script type="text/javascript" language="javascript">
	function checkStatus() {
		httpObject = getHTTPObject();
		if (httpObject != null) {
			httpObject.open("GET", "/searchadmin/status", true);
			httpObject.send(null);
			httpObject.onreadystatechange = updateStatus;
		}
	}
	
	function updateStatus()
	{
		if (httpObject.readyState == 4) {
			var status = eval("(" + httpObject.responseText + ")");
			var status_area = document.getElementById('status_area');
			var build_status = document.getElementById('build_status');
			
			if (status.building)
			{
				status_area.style.display = "inline";
				build_status.innerHTML = "Building...";
				
				var sql_stat = document.getElementById('sql_stat');
				var index_stat = document.getElementById('index_stat');
				var progress = document.getElementById('progress_bar').childNodes[0];
				
				switch(status.sql_stat) {
					case 1:
						sql_stat.style.backgroundColor = "green"; break;
					case 2:
						sql_stat.style.backgroundColor = "red"; break;
					case 0:
					default:
						sql_stat.style.backgroundColor = "gray";
				}
				
				switch(status.index_stat) {
					case 0:
						index_stat.style.backgroundColor = "yellow"; break;
					case 1:
						index_stat.style.backgroundColor = "green"; break;
					case 2:
						index_stat.style.backgroundColor = "red"; break;
					case 0:
					default:
						index_stat.style.backgroundColor = "gray";
				}
				
				progress.style.width = "" + status.progress + "%";
				setTimeout(checkStatus, 2000);
			} else {
				status_area.style.display = "none";
				build_status.innerHTML = "Ready";
				
				var index_size = document.getElementById('index_size');
				var index_count = document.getElementById('index_count');
				
				index_size.innerHTML = status.size;
				index_count.innerHTML = status.count;
			}
		}
	}
</script>
<div class="content-box">
	<div class="header">
		<div class="tools">
			<a href="/searchadmin/rebuild" title="Rebuild">
				<div class="refresh-icon-medium"></div>
			</a>
		</div>
		<h1>Search Index Status</h1>
	</div>
 	<div class="body">
		<table>
			<tr>
				<td>Index Size</td>
				<td id="index_size">Checking...</td>
			</tr>
			<tr>
				<td>Document Count</td>
				<td id="index_count">Checking...</td>
			</tr>
			<tr>
				<td>Status</td>
				<td id="build_status">Checking...</td>
			</tr>
		</table>
		<table id="status_area" style="display: none">
			<tr>
				<td>Oracle Status</td>
				<td style="text-align: right"><div id="sql_stat" class="indicator"></div></td>
			</tr>
			<tr>
				<td>Index Status</td>
				<td style="text-align: right"><div id="index_stat" class="indicator"></div></td>
			</tr>
			<tr>
				<td colspan="2"><div id="progress_bar"><div></div></div></td>
			</tr>
		</table>
 	</div>
</div>
<script type="text/javascript" language="javascript">
	checkStatus();
</script>