@extends('layouts.default')

@section('content')

<style type="text/css" media="all">

.on {
    background:blue !important;
}

.bl-min {
    float:left;
    width:7px;
    height:7px;
    background:#efefef;
    margin:1px;
    font-size:6px;
}

.hd-min {
    background:#ffffff;
    width:14px;
}

</style>

<div class="bl-min hd-min">CD</div>
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<br />
<div class="bl-min hd-min">MW</div>
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<br />
<div class="bl-min hd-min">CD</div>
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<br />
<div class="bl-min hd-min">MW</div>
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min on"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<div class="bl-min"></div> 
<br />

@stop
