<div class="content-box">
	<div class="header">
		<h1>Create Role</h1>
	</div>
	<div class="body">
		<?php if (isset($this->errors)) : ?>
		<?php foreach ($this->errors as $error) : ?>
		<div><?php echo $error ?></div>
		<?php endforeach ?>
		<?php endif ?>
		<form action="" method="post" id="create_role">
			<fieldset>
				<dl>
					<dt><label for="name">Role Name</label></dt>
					<dd>
						<input name="name" validate="strlen 1 32; words" />
						<error for="name">A role name must consist of letters and numbers and be 1-32 characters.</error>
					</dd>
				</dl>
			</fieldset>
			<input type="submit" value="Create Role" />
		</form>
	</div>
</div>