<?php
$this->headLink()->appendStylesheet('/scripts/css/icons.css');
?>
<div class="content-box">
	<div class="header">
		<h1>Roles</h1>
	</div>
	<div class="body">
		<table>
			<col style="width: 20px" />
			<col style="width: 50px" />
			<col />
			<thead>
				<tr>
					<th></th>
					<th>ID</th>
					<th>Role Name</th>
				</tr>
			</thead>
			<tbody>
				<?php $alt = 0; foreach($this->roles as $role) : ?>
				<tr <?php if ($alt ^= 1) : ?>class="alt"<?php endif ?>>
					<td>
						<a href="/roles/delete/role/<?php echo $role->id ?>" title="Delete Role">
							<img class="icon" src="/images/icons/trash_16.png" alt="trash icon" />
						</a>
					</td>
					<td><?php echo $role->id ?></td>
					<td><a href="/roles/edit/role/<?php echo $role->id ?>"><?php echo ucwords($role->name) ?></a></td>
				</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</div>
</div>