<div class="content-box"> 
    <div class="header">
		<h1>Order #<?php echo $this->order->ORDER_ID; ?> for <?php echo $this->order->TYPE_NAME ?> store <?php echo $this->order->STORE_CODE ?></h1>
    </div>
	<div class="body">
        <table>
			<tr>
				<td style="font-weight: bold">Current Stage</td>
				<td style="text-align: right"><?php echo $this->order->STAGE_NAME; ?></td>
			</tr>
			<tr class="alt">
				<td style="font-weight: bold">Line Items</td>
				<td style="text-align: right"><?php echo $this->order->LINE_ITEM_COUNT; ?></td>
			</tr>
			<tr>
				<td style="font-weight: bold">Retail Value</td>
				<td class="money">$<?php echo number_format($this->order->RETAIL_TOTAL, 2); ?></td>
			</tr>
			<?php if (isset($this->order->COST_TOTAL)) : ?>
			<tr class="alt">
				<td style="font-weight: bold">Total Cost</td>
				<td class="money">$<?php echo number_format($this->order->COST_TOTAL, 2); ?></td>
			</tr>
			<?php endif; ?>
        </table>
	</div>
</div>