<?php 
if (!empty($this->order->items)) : 
	$colCount = 6;
	if ($this->order->access->write)
		$colCount += 2;
		
	if ($this->order->STORE_TYPE != 0)
		$colCount += 3;
?>
<div class="content-box"> 
	<form action="/orders/update/order/<?php echo $this->order->ORDER_ID ?>" method="post" id="items_form">
		<div class="body">
	        <table>
	            <thead>
	                <tr>
	                    <th>Item</th>
	                    <th>Description</th>
	                    <th>Qty</th>
	                    <th style="width: 0; padding-left: 5px;">Retail</th>
	                    <th style="width: 0; padding-left: 5px;">Total</th>
	                    <?php if ($this->order->STORE_TYPE != 0) : ?>
	                    <th style="width: 0; padding-left: 5px;">Discount</th>
	                    <th style="width: 0; padding-left: 5px;">Cost</th>
	                    <th style="width: 0; padding-left: 5px;">Total</th>
	                    <?php endif; ?>
	                </tr>
	            </thead>
	            <tbody>
	                <?php 
					$alt = 0;						
					foreach ($this->order->items as $dname => $items) : ?>
	                <tr>
	                    <th colspan="<?php echo $colCount ?>"><?php echo $dname; ?></th>
	                </tr>
	                <?php $alt = 0; foreach ($items as $item) : ?>
	                <tr <?php if ($alt ^= 1) : ?>class="alt"<?php endif; ?>>
	                    <td>
	                    	<?php echo $item->ITEM_NO; ?>
	                	</td>
	                    <td><?php echo $item->DESCRIPTION ?></td>
	                    <td>
	                    	<?php echo $item->ITEM_QTY ?> x <?php echo $item->CASE_QTY ?>
	                    </td>
	                    <td class="money">
	                        <?php if (isset($item->RETAIL_PRICE)) : ?>
	                        <?php echo '$'. number_format($item->RETAIL_PRICE, 2); ?>
	                        <?php endif ?>
	                    </td>
	                    <td class="money">
	                    	<?php if (isset($item->RETAIL_PRICE)) : ?>
	              			<?php echo '$' . number_format($item->RETAIL_TOTAL, 2); ?>
	              			<?php endif ?>
	                    </td>
	                    <?php if ($this->order->STORE_TYPE != 0) : ?>
	                    <td class="money">
	                        <?php echo (isset($item->MARKDOWN) ? number_format($item->MARKDOWN, 2) . '%' : '') ?>
	                    </td>
	                    <td class="money">
	                        <?php if (isset($item->COST)) : ?>
	                        <?php echo '$' . number_format($item->COST, 2); ?>
	                        <?php endif ?>
	                    </td>
	                    <td class="money">
	                    	<?php if (isset($item->COST)) : ?>
	              			<?php echo '$' . number_format($item->COST_TOTAL, 2); ?>
	              			<?php endif ?>
	                    </td>
	                    <?php endif ?>
	                </tr>
	                <?php if (isset($item->ITEM_COMMENT)) : ?>
	                <tr class="comment_entry" style="visibility: collapse">
	                	<td colspan="<?php echo $colCount ?>">
	                		<label>Comment:</label> 
                			<input type="text" name="<?php echo $item->ITEM_NO; ?>_comment" value="<?php echo $item->ITEM_COMMENT ?>" />
	                	</td>
	                </tr>
	                <?php endif; ?>
	                <?php endforeach; ?>
	                <?php endforeach; ?>
	            </tbody>
	        </table>
    	</div>
    </form>
</div>
<?php endif; ?>