<?php 
$this->headTitle('Passport New Hire'); 
$this->headLink()
	->appendStylesheet('/scripts/css/new-hire.css')
	->appendStylesheet('/scripts/css/addon/nogray_calendar_vs1.css');

$this->headScript()
	->appendFile('/scripts/js/addon/nogray_date_calendar_vs1_min.js')
	->appendFile('/scripts/js/new-hire.js');
?>
<div class="content-box">
	<div class="header">
		<h1>New Hire Form</h1>
	</div>
	<div class="body">
		<?php echo $this->newHireForm ?>
	</div>
</div>