<script type="text/javascript" language="javascript" src="/scripts/js/menu.js"></script>
<ul class="menu" id="nav">
	<li class="menu-closed">
		<h1 onClick="showMenu(this.parentNode)">
			Product
		</h1>
		<ul>
			<li><a href="/items/">Catalogue</a></li>
			<li><a href="/orders/">Review Orders</a></li>
			<!-- <li><a href="/items/highlights/">Product Highlights</a></li> -->
			<li><a target="new" href="http://www.earthboundtrading.com/images/graphicorderform/graphic_order_form.htm">Graphics Order</a></li>
			<li><a target="new" href="http://www.earthboundtrading.com/images/signorderform/sign-checklist-master.htm">Sign Order</a></li>
		</ul>
	</li>
	<!-- <li class="menu-closed">
		<h1 onClick="showMenu(this.parentNode)">
			Management
		</h1>
		<ul>
			<li>My Account</li>
			<li>Site Admin</li>
		</ul>
	</li> -->
	<li class="menu-closed">
		<h1 onClick="showMenu(this.parentNode)">
			Other
		</h1>
		<ul>
			<li><a href="http://old.ebtpassport.com/email_upload/view_results.php">Email Upload</a></li>
			<li><a href="http://www.earthboundtrading.com/images/payroll_submittal.htm">Payroll Form</a></li>
			<li><a href="http://www.earthboundtrading.com/images/discrepancy_form/discrepancy_form.htm">Inventory Discrepancy</a></li>
		</ul>
	</li>
	<li class="menu-open">
		<h1 onClick="showMenu(this.parentNode)">
			Passport
		</h1>
		<ul>
			<li><a href="/myaccount">My Account</a></li>
			<li><a href="/news">News</a></li>
			<li><a href="/downloads">Documents</a></li>
			<li>About</li>
			<li>Help</li>
			<li><a href="/auth/logout/">Logout</a></li>
		</ul>
	</li>
	<li class="menu-bottom">
		<h1><a href="/">Passport Menu</a></h1>
	</li>
</ul>