<?php 
	$this->headTitle("Passport Home");
	$this->layout()->help = array(
		'title' => 'Passport Home',
		'body' => 'This page has the latest news from EBT companies, click any of the options on the right hand menu to get started with more features.');
?>
<?php foreach ($this->articles as $article) : ?>
<div class="content-box">
	<div class="header">
		<h1><?= $article->SUBJECT ?></h1>
		<h2>
			posted on <?= $article->POSTED_ON ?> by 
			<?= $article->FIRST_NAME ?> <?= $article->LAST_NAME ?>
		</h2>
	</div>
 	<div class="body">
	 &nbsp;&nbsp;&nbsp;&nbsp;
	 <?= $article->BODY ?>
 	</div>
</div>
<?php endforeach; ?>