<?php

?>
<div class="content-box">
	<div class="header">
		<h1>Upload to <?php echo join(' &gt; ', array_map('htmlentities', $this->cwd)) ?></h1>
	</div>
	<div class="body">
		<form enctype="multipart/form-data" action="" method="POST">
			<input type="hidden" name="MAX_FILE_SIZE" value="5242880" />
			Choose a file to upload: <input name="uploadedfile" type="file" /><br />
			<input type="submit" value="Upload File" />
		</form>
	</div>
</div>