<?php echo $this->doctype('XHTML1_STRICT') ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<?php 
			/* Set default headers */
			$this->headLink(array('rel' => 'icon', 'type'=> 'icon/ico', 'href' => '/images/favicon.ico'));
			$this->headLink()->prependStylesheet('/scripts/css/master.css');
			$this->headLink()->prependStylesheet('/scripts/css/icons.css');
			$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
            	->appendHttpEquiv('Content-Language', 'en-US');
                 
            $this->headScript()
            	->prependFile('/scripts/js/cart.js')
            	->prependFile('/scripts/js/loading.js')
            	->prependFile('/scripts/js/addon/mootools-debug.js');
            	
            /* Render headers */
            echo $this->headTitle();
        	echo $this->headLink();
        	echo $this->headMeta();
        	echo $this->headScript();
        	echo $this->headStyle();
        ?>
	</head>
	<body>
		<?php if (isset($this->layout()->help)) : ?>
		<div id="help-box">
			<h1><?= $this->layout()->help['title'] ?></h1>
			<p><?= $this->layout()->help['body'] ?></p>
		</div>
		<?php endif; ?>
		<div id="top-panel">
  			<div style="text-align: left">
  				<img src="/images/Tag_02.jpg" alt="EBT Logo" style="text-align: center" />
  			</div>  
		</div>
		<div id="breadcrumb-panel">
			Welcome <?php echo Zend_Auth::getInstance()->getIdentity()->first_name ?>
		</div>
		<div id="right_panel">
			<?php echo $this->action('index', 'nav') ?>
			<div id="cart"><?php echo $this->action('index', 'cart') ?></div>
			<div class="content-box" id="messages" <?php if (empty($this->messages)) : ?>style="display: none<?php endif; ?>">
				<div class="header">
					<h1>Errors</h1>
				</div>
				<div class="body">
					<ul>
						<?php if (isset($this->messages)) : ?>
						<?php foreach ($this->messages as $message) : ?>
						<li><?php echo $message; ?>
						<?php endforeach; ?>
						<?php endif; ?>
					</ul>
				</div>
			</div>
			<br />
		</div>
		<div id="content-area">
			<?php echo $this->layout()->content; ?>
			<br />
		</div>
		<div id="loading-status">
			Loading... <img src="/images/ajax-loader.gif" title="Loading..." alt="Loading..." />
		</div>
	</body>
</html>
