<?php
# ----------------------------------------------------
# -----
# ----- This script was generated by PHP-Form Wizard 1.2.6 on 1/20/2009 at 5:24:38 PM
# -----
# ----- http://www.tools4php.com
# -----
# ----------------------------------------------------


// Receiving variables
@$pfw_ip= $_SERVER['REMOTE_ADDR'];
@$Store = addslashes($_POST['Store']);
@$TESTFIELD = addslashes($_POST['TESTFIELD']);

// Validation
if (strlen($Store) !=3)
{
die("<p align='center'><font face='Arial' size='3' color='#FF0000'>Please enter a valid store</font></p>");
}

if (strlen($Store) == 0 )
{
die("<p align='center'><font face='Arial' size='3' color='#FF0000'>Please enter a valid store</font></p>");
}

//Sending Email to form owner
$pfw_header = "From: $Store\n"
  . "Reply-To: $Store\n";
$pfw_subject = "test";
$pfw_email_to = "renee@earthboundtrading.com";
$pfw_message = "Visitor's IP: $pfw_ip\n"
. "Store: $Store\n"
. "TESTFIELD: $TESTFIELD\n";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

//Sending auto respond Email to visitor
$pfw_header = "From: renee@earthboundtrading.com\n"
  . "Reply-To: renee@earthboundtrading.com\n";
$pfw_subject = "test";
$pfw_email_to = "$Store";
$pfw_message = "test";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

//saving record in a text file
$pfw_file_name = "test.csv";
$pfw_first_raw = "Store,TESTFIELD\r\n";
$pfw_values = "$Store,$TESTFIELD\r\n";
$pfw_is_first_row = false;
if(!file_exists($pfw_file_name))
{
 $pfw_is_first_row = true ;
}
if (!$pfw_handle = fopen($pfw_file_name, 'a+')) {
 die("Cannot open file ($pfw_file_name)");
 exit;
}
if ($pfw_is_first_row)
{
  if (fwrite($pfw_handle, $pfw_first_raw ) === FALSE) {
  die("Cannot write to file ($pfw_filename)");
  exit;
  }
}
if (fwrite($pfw_handle, $pfw_values) === FALSE) {
  die("Cannot write to file ($pfw_filename)");
  exit;
}
fclose($pfw_handle);

//saving record to MySQL database


@$pfw_strQuery = "INSERT INTO `ebt`(`CODE`,`QTY`)VALUES (\"$Store\",\"$TESTFIELD\")" ;
@$pfw_host = "192.168.1.233";
@$pfw_user = "renee";
@$pfw_pw = "wer8ing4u";
@$pfw_db = "test";
$pfw_link = mysql_connect($pfw_host, $pfw_user, $pfw_pw);
if (!$pfw_link) {
 die('Could not connect: ' . mysql_error());
}
$pfw_db_selected = mysql_select_db($pfw_db, $pfw_link);
if (!$pfw_db_selected) {
die ('Can not use $pfw_db : ' . mysql_error());
}

//insert new record
$pfw_result = mysql_query($pfw_strQuery);
if (!$pfw_result) {
 die('Invalid query: ' . mysql_error());
}
mysql_close($pfw_link);

 echo("<p align='center'><font face='Arial' size='3' color='#FF0000'>Thanks for filling this out!<br></font></p>");
?>
