<?php
# ----------------------------------------------------
# -----
# ----- This script was generated by PHP-Form Wizard 1.2.6 on 1/22/2009 at 2:53:35 PM
# -----
# ----- http://www.tools4php.com
# -----
# ----------------------------------------------------


// Receiving variables
@$pfw_ip= $_SERVER['REMOTE_ADDR'];
@$recipient = addslashes($_POST['recipient']);
@$subject = addslashes($_POST['subject']);
@$success = addslashes($_POST['success']);
@$env_report = addslashes($_POST['env_report']);
@$Store = addslashes($_POST['Store']);
@$quest1 = addslashes($_POST['quest1']);
@$textarea2 = addslashes($_POST['textarea2']);

// Validation
//saving record to MySQL database


@$pfw_strQuery = "INSERT INTO `ebt`(`ITEM`,`ITEM`,`QTY`)VALUES (\"$Store\",\"$quest1\",\"$textarea2\")" ;
@$pfw_host = "192.168.1.233";
@$pfw_user = "renee";
@$pfw_pw = "wer8ing4u";
@$pfw_db = "test";
$pfw_link = mysql_connect($pfw_host, $pfw_user, $pfw_pw);
if (!$pfw_link) {
 die('Could not connect: ' . mysql_error());
}
$pfw_db_selected = mysql_select_db($pfw_db, $pfw_link);
if (!$pfw_db_selected) {
die ('Can not use $pfw_db : ' . mysql_error());
}

//insert new record
$pfw_result = mysql_query($pfw_strQuery);
if (!$pfw_result) {
 die('Invalid query: ' . mysql_error());
}
mysql_close($pfw_link);

 echo("<p align='center'><font face='Arial' size='3' color='#FF0000'>Thanks!</font></p>");
?>
