<?php
# ----------------------------------------------------
# -----
# ----- This script was generated by PHP-Form Wizard 1.2.6 on 1/22/2009 at 2:14:17 PM
# -----
# ----- http://www.tools4php.com
# -----
# ----------------------------------------------------


// Receiving variables
@$pfw_ip= $_SERVER['REMOTE_ADDR'];
@$recipient = addslashes($_POST['recipient']);
@$subject = addslashes($_POST['subject']);
@$success = addslashes($_POST['success']);
@$env_report = addslashes($_POST['env_report']);
@$Store = addslashes($_POST['Store']);
@$quest1 = addslashes($_POST['quest1']);

// Validation
//Sending Email to form owner
$pfw_header = "From: $Store\n"
  . "Reply-To: $Store\n";
$pfw_subject = "Test Reply";
$pfw_email_to = "renee@earthboundtrading.com";
$pfw_message = "Visitor's IP: $pfw_ip\n"
. "recipient: $recipient\n"
. "subject: $subject\n"
. "success: $success\n"
. "env_report: $env_report\n"
. "Store: $Store\n"
. "quest1: $quest1\n";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

//saving record to MySQL database


@$pfw_strQuery = "INSERT INTO `ebt`(`QTY`,`CODE`,`ITEM`)VALUES (\"$recipient\",\"$Store\",\"$quest1\")" ;
@$pfw_host = "192.168.1.233";
@$pfw_user = "renee";
@$pfw_pw = "wer8ing4u";
@$pfw_db = "test";
$pfw_link = mysql_connect($pfw_host, $pfw_user, $pfw_pw);
if (!$pfw_link) {
 die('Could not connect: ' . mysql_error());
}
$pfw_db_selected = mysql_select_db($pfw_db, $pfw_link);
if (!$pfw_db_selected) {
die ('Can not use $pfw_db : ' . mysql_error());
}

//insert new record
$pfw_result = mysql_query($pfw_strQuery);
if (!$pfw_result) {
 die('Invalid query: ' . mysql_error());
}
mysql_close($pfw_link);

 echo("<p align='center'><font face='Arial' size='3' color='#FF0000'>Thanks!</font></p>");
?>
